### ISSUE TITLE
JSON LD

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#15]
The Libraries mentioned on https://json-ld.org/ namely
- https://github.com/RDFLib/rdflib-jsonld
  -  rdf graph specific
- https://github.com/digitalbazaar/pyld 
  - not really documented

seem not usable. Do we need a JSON LD lib to properly handle e.g. namespaces for userextensions?

**Comment by RalphTro** [comment]
A pity... turning to your question: IMO, not necessarily. As the namespaces/CURIEs are properly defined in the context header (see e.g. https://github.com/gs1/EPCIS/blob/master/JSON/Example_9.6.1-with-comment.json), I think a "normal" JSON lib should do, what is your take on that?

**Comment by Echsecutor** [comment]
I do the namespace replacing and  "#" keys "by hand" now, json ld is hence not really needed
