### ISSUE TITLE
missing attributes

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#17]
e.g.
type="urn:epcglobal:cbv:btt:desadv"
is missing from https://github.com/RalphTro/epcis-event-hash-generator/blob/master/tests/examples/epcisDocWithVariousEventTypes.prehashes

**Comment by Echsecutor** [comment]
`bizTransactionList` was missing `type` in the ordering specs

**Comment by Echsecutor** [comment]
@RalphTro actually `bizTransactionList` appears in position 7 or 17 depending on the event type. Can we please make the ordering of fields independend of the event type? I.e. put the list in position 17, say, regardless of the type. (or 7, but make it unique, please).

**Comment by RalphTro** [comment]
Well...in this case, we would introduce an exception to our principle to stick to the EPCIS event data model. Unfortunately, for the TransactionEvent, it just appears at this position.

**Comment by Echsecutor** [comment]
actually the current algorithm has a bug and adds the list twice, which apparently went unrecognised so far. I have now moved it down to pos 17.
