### ISSUE TITLE
Consider readPoint/bizLocation "id" attribute in JSON/JSON-LD

### ISSUE THREAD

**Issue by RalphTro** [RalphTro/epcis-event-hash-generator#24]
As of the latest discussion in the EPCIS/CBV 2.0 group, readPoint/bizLocation ID, when expressed in JSON/JSON-LD, now looks as follows:
"readPoint": {"id": "urn:epc:id:sgln:0614141.07346.1234"},

Previously, we envisioned the following data structure:
"readPoint": "urn:epc:id:sgln:0614141.07346.1234",

ToDo: check/adjust algorithm

**Comment by Echsecutor** [comment]
AFAIK all emxamples are already in 
```
        "readPoint": {"id": "urn:epc:id:sgln:4012345.00011.987"},
```
format and all tests are green. -> anything todo?

**Comment by Echsecutor** [comment]
ah, I found an old version in `expected_equal/ReferenceEventHashAlgorithm.json` and adapted this one. tests still green ;)

**Comment by RalphTro** [comment]
If the addition of the 'id' attribute in *.jsonld formatted events still yields the same hash values, that's great! No more todo then... thanks!
