### ISSUE TITLE
Digital Link Syntax for EPCs

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#31]
Ralph wrote a separate Normalizer for this

**Comment by Echsecutor** [comment]
@RalphTro Interesting question that came up during testing:

Do we normalise values only from standard fields or also form user extension fields? 

In `examples/SensorDataExamples.xml` there is a `{https://ns.example.com/epcis}machine` with value `urn:epc:id:giai:4012345.ABC`. Should normalise this value to `https://id.gs1.org/8004/4012345ABC`? I vote yes. ;)

**Comment by RalphTro** [comment]
Good catch, @Echsecutor ! 
I tend to agree with you. This way, it's more unambiguous.
