### ISSUE TITLE
GS1 Web Voc Canonicalisation of standard voc elements

### ISSUE THREAD

**Issue by RalphTro** [RalphTro/epcis-event-hash-generator#32]
See # 14:
If present, any URN-based standard vocabulary value (starting with ‘urn:epcglobal:cbv’) SHALL be expressed in its corresponding GS1 Web Vocabulary URI equivalent (starting with ‘https://ns.gs1.org’). Example: ‘urn:epcglobal:cbv:bizstep:receiving’ --> ‘https://ns.gs1.org/cbv/BizStep-receiving’

**Comment by Echsecutor** [comment]
The following need to be replaced:
```
return (inputStr.replace('urn:epcglobal:cbv:bizstep:', 'https://gs1.org/voc/Bizstep-').replace('urn:epcglobal:cbv:disp:', 'https://gs1.org/voc/Disp-').replace('urn:epcglobal:cbv:btt:', 'https://gs1.org/voc/BTT-').replace('urn:epcglobal:cbv:sdt:', 'https://gs1.org/voc/SDT-').replace('urn:epcglobal:cbv:er:', 'https://gs1.org/voc/ER-'))
```

where the url needs to be *ns*.gs1....
