### ISSUE TITLE
Add Web Service API Tests

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#48]
Currently the API Code in `webapi/api.py` is not tested et all (i.e. "legacy").

**Comment by RalphTro** [comment]
Dear @Echsecutor ,
As this issue has no assignee yet - will you take care of this?

**Comment by dakbhavesh** [comment]
Hi @Echsecutor, This issue is no more relevant as we have decided to remove support of web service hence we can close it.
