### ISSUE TITLE
Wanted: Documentation of the Webservice

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#50]
The documentation of the web serice container went missing. It is expceted to be here: https://github.com/RalphTro/epcis-event-hash-generator/packages/484860

**Comment by RalphTro** [comment]
Dear @dakbhavesh  and @Echsecutor ,
What is your take on how to proceed with this issue? Can wen close it?

**Comment by dakbhavesh** [comment]
Hi @RalphTro, I will take care of adding documentation of the web service container. Let's keep the issue open and have it assigned it to me only.

**Comment by dakbhavesh** [comment]
Hi @RalphTro, As discussed we are going to remove web service support as Python-based implementation is more or less experimental as of now, and support for web service may confuse user that it is 100% ready for production.
We can close this ticket after pull request #111 is merged.

FYI: @Echsecutor

**Comment by RalphTro** [comment]
Agreed. Happy to mark this issue as closed. 
Many thanks again, @dakbhavesh!
