### ISSUE TITLE
DeprecationWarning from gtin package

### ISSUE THREAD

**Issue by Echsecutor** [RalphTro/epcis-event-hash-generator#52]
since the inclusion of the dl normalisation, the hashing generator depends on the gtin package which pulls in quite a few more dependencies, one of them being deprecated.

Upgrading the gtin package upstream would be the preferred solution. Otherwise we might have to look into removing the dependency by re-implementing the actually needed functionality.

**Comment by RalphTro** [comment]
Check whether alternative package is available or issue PR to package or write it ourselves

**Comment by RalphTro** [comment]
Preference: PR

**Comment by RalphTro** [comment]
Dear @Echsecutor ,
I just had a look at the gtin package (https://pypi.org/project/gtin/) and couldn't find a deprecation warning. Can you? It was updated April 2022, so it may be not unlikely that the authors addressed the issue you were referring to back in 2021. WDYT?
Kind regards,
Ralph

**Comment by dakbhavesh** [comment]
Dear @Echsecutor / @RalphTro, I have raised an issue on gtin repository as latest version is not generating gtin as expected.

Reference: https://github.com/enorganic/gtin/issues/9

Please feel free to add more examples or behavior with Linux/Windows platform.

**Comment by RalphTro** [comment]
Replaced code
