### ISSUE TITLE
Date format with pre-hash string

### ISSUE THREAD

**Issue by clementh59** [RalphTro/epcis-event-hash-generator#54]
Hi,

In rule 8 of the algorithm, you say: 
```
All timestamps SHALL be expressed in UTC; the zero UTC offset SHALL be expressed with the capital letter 'Z'.
```

which means that timestamps can have a time offset, right?

This is indeed the case of the `time` field of a `sensorMetadata`. If you look at the example `epcisDocWithSensorDataObjectEvent.jsonld`, the pre-hash string is:
```
sensorMetadatatime=2019-04-02T14:05:00.000+01:00
```
(It keeps the offset so everything is working as expected)

However, when you look at the pre-hash string of the last event in `SensorDataExamples.xml`, we have this field:
```
<declarationTime>2020-09-29T15:00:00.000+02:00</declarationTime>
```
But in the pre-hash string, it converts the date like this:
```
declarationTime=2020-09-29T13:00:00.000
```

Is it the expected output? If it is the case, do I miss something in the algorithm?

Thanks a lot.

**Comment by RalphTro** [comment]
Dear @clementh59 , 

Good catch! You are correct. *All* timestamps should be converted to zero UTC. 

I hope you do not need a fix urgently? ;-) 

Kind regards and thanks again;
Ralph

**Comment by clementh59** [comment]
Dear @RalphTro ,

I see, thanks!

No, that's ok, I just want to be sure I understand the algorithm correctly :)

Regards,

Clément
