### ISSUE TITLE
Replace isA with type for JSON-LD as per new EPCIS JSON/JSON-LD Schema

### ISSUE THREAD

**Issue by dakbhavesh** [RalphTro/epcis-event-hash-generator#63]
Update the algorithm & examples to replace `isA` field with `type` as per recent changes in EPCIS event schema

Reference: https://github.com/gs1/EPCIS/blob/master/JSON-Schema/EPCIS-Event-JSON-Schema.json

FYI: @Echsecutor , @RalphTro

**Comment by RalphTro** [comment]
Many thanks for adding this issue/submitting the PR, @dakbhavesh! 

Once the spec is ratified and we have some bandwidth, we can tidy everything up with joint forces.

**Comment by dakbhavesh** [comment]
Closing this issue as PR#64 is approved.
