### ISSUE TITLE
certificationInfo, exception, coordinateReferenceSystem 

### ISSUE THREAD

**Issue by RalphTro** [RalphTro/epcis-event-hash-generator#75]
- Add these fields to the canonical property order

- Prepare example(s) in *.xml and *.jsonld

- Adjust readMe

**Comment by Aravinda93** [comment]
Hi @RalphTro 

We just wanted to confirm the order of these elements in the pre-hash string. Should it appear at the bottom or before extensions? If possible can you please add these elements as a part of property in the [table](https://github.com/RalphTro/epcis-event-hash-generator#canonical-property-order) that you have provided?

**Comment by RalphTro** [comment]
Hi @Aravinda93 ,

As things stand now, we most probably will insert these three fields in the property order as follows: 
…
sensorReport (type, **exception**, deviceID, deviceMetadata, rawData, dataProcessingMethod, time, microorganism, chemicalSubstance, value, component, stringValue, booleanValue, hexBinaryValue, uriValue, minValue, maxValue, meanValue, sDev, percRank, percValue, uom, **coordinateReferenceSystem**)
…
…
3. eventTimeZoneOffset
4. **certificationInfo**
5. epcList – epc
…

As to your question: gladly - the readMe wil be updated as part of an upcoming PR - stay tuned! 

Have a nice weekend and kind regards,
Ralph

**Comment by Aravinda93** [comment]
Dear @RalphTro,

Thanks a lot for the confirmation on the order for these elements.

Have a nice weekend and kind regards,
Aravinda

**Comment by RalphTro** [comment]
Sebastian/Ralph to have a look at PR 81

**Comment by RalphTro** [comment]
PR 81 deployed
