### ISSUE TITLE
Ordering issue for child elements such as bizTransactionList, sourceList, and destinationList

### ISSUE THREAD

**Issue by ShaikDayan** [RalphTro/epcis-event-hash-generator#80]
Hello Everyone,
While testing and comparison we came across this issue 
Currently pre-hash string generate bizTransaction/source/destination first and then the type which is not correct.
As per the GS1 standards https://ref.gs1.org/standards/cbv/#page=96  we need to have type first.

Example

biztransactionList (biztransaction,type) 
Current Prehashing behaviour: biztransaction&type

Expected Prehashing behaviour: type&biztransaction

**Comment by RalphTro** [comment]
Dear @ShaikDayan , 

Thanks a lot for making us aware of this issue! You are correct. 

@Echsecutor: e.g. when I executed the epcis even hash generator for one of our existing examples (in this case, "epcisDocWithShippingAndTransportingEvent" (no matter which of the two file extensions), the following pre-hash-string is returned: 
...
```
bizTransactionList
bizTransaction=urn:epcglobal:cbv:bt:4012345000009:ASN1099
type=https://ref.gs1.org/cbv/BTT-desadv
```
...
At the same time, `type `should appear prior to the corresponding `bizTransaction `ID. (BTW: I am pretty sure that this worked  fine in a previous release.)

Would you mind having a look into this matter once you have some bandwidth? 

Many thanks and kind regards,
Ralph

**Comment by dakbhavesh** [comment]
Dear @RalphTro, As I was trying to understand various reported issues I thought it will be quick for me to verify the history of PROP_ORDER. Below is the screenshot history which shows that the property order was altered for attributes of source list, destinationList, etc. however it looks like the order was kept as is or may be reversed during the course of drafting the CBV/EPCIS 2.0 standard. 

<img width="1780" alt="Screenshot 2023-01-25 at 5 17 21 PM" src="https://user-images.githubusercontent.com/305704/214556420-0e59c0a1-2079-4dad-84c7-517786033f9b.png">


I am happy to take the issue up and fix the property order that matches with https://ref.gs1.org/standards/cbv/#page=96.

FYI: @ShaikDayan

**Comment by RalphTro** [comment]
Dear @dakbhavesh , 
Thanks! Good catch. Yes, I think reversing it (again) should do the trick. 
@Echsecutor: do you remember the reason why the property order was adjusted back then? If not, I think that this was just an oversight which e.g. Bhavesh can easily fix. 
Kind regards,
Ralph

**Comment by ShaikDayan** [comment]
Dear @RalphTro,
I tried to change in PROP_ORDER but still the issue persists, I believe we need to make few change in the code currently looking into it.
Regards,
Dayan

**Comment by RalphTro** [comment]
Sebastian + Ralph as reviewer

**Comment by RalphTro** [comment]
Can be closed from my POV (as also confirmed by @dakbhavesh). 

Many thanks again for the related PR!
