### ISSUE TITLE
SensorElementList should only appear once 

### ISSUE THREAD

**Issue by RalphTro** [RalphTro/epcis-event-hash-generator#83]
Dear All, 

When I executed the file `CertificationInfoAndSensorReportWithCRS.jsonld` , the field `sensorElementList` appeared twice in the pre-hash string: 

```
...
sensorElementList
sensorElement
sensorMetadata
time=2023-01-11T11:05:00.000Z
bizRules=https://id.gs1.org/253/4012345000054987
sensorReport
type=https://gs1.org/voc/Dimensionless
exception=https://gs1.org/voc/ALARM_CONDITION
coordinateReferenceSystem=http://www.opengis.net/def/crs/EPSG/0/27700
sensorElementList
sensorElement
sensorMetadata
...
```

Similar to e.g. bizTransactionList, this field should only appear once. 

Kind regards,
@RalphTro

**Comment by dakbhavesh** [comment]
Dear @RalphTro, I checked with Aravinda about how pre-hashes are produced in Java and JavaScript based implementation and got to know that they are also creating separate sensorElementList only for enclosed user extension fields. However, if you think that it's not the right way to generate pre-hash then we will surely fix the logic.

OpenEPCIS Hash Generator Link: https://tools.openepcis.io/openepcis-ui/EventHash/

Our suggestion is to enrich [CBV standard ](https://ref.gs1.org/standards/cbv/#page=95) so that we all are on the same page about the expected pre-hash structure for all important permutations & combinations.

**Comment by RalphTro** [comment]
Dear @dakbhavesh ,
Thanks a lot for checking this! 
As to your suggestion: happy to discuss to which extent it makes sense to make our specification more clear. 
I think an appropriate place for adding some language would be:

> 11. All child elements as part of a list (e.g. epc in epcList, bizTransaction in bizTransactionList, etc.) SHALL be sequenced according to their case-sensitive lexical ordering, considering UTF-8/ASCII code values of each successive character.

This *may* not be explicit enough that the parent field should only appear once. From your POV, which additional language would make sense? 
E.g. sth. like "The name of a field denoting a list (e.g. epcList, bizTransactionList, sensorElementList) SHALL only appear once."? Please go ahead and suggest any modification which would make sense from your perspective. 

Kind regards,
Ralph

**Comment by dakbhavesh** [comment]
Dear @RalphTro, In my opinion, the definition/language in point#11 looks fine however we should rather update the canonical ordering of elements as we are missing mention of the user extension field there.

For example,

As is:

```
23. sensorElement (
sensorMetadata (time, startTime, endTime, deviceID, deviceMetadata, rawData, dataProcessingMethod, bizRules),
sensorReport (type, deviceID, deviceMetadata, rawData, dataProcessingMethod, time, microorganism,
chemicalSubstance, value, component, stringValue, booleanValue, hexBinaryValue, uriValue, minValue, maxValue,
meanValue, sDev, percRank, percValue, uom))
```

To be:

```
23. sensorElement (
sensorMetadata (time, startTime, endTime, deviceID, deviceMetadata, rawData, dataProcessingMethod, bizRules, userExtensions),
sensorReport (type, deviceID, deviceMetadata, rawData, dataProcessingMethod, time, microorganism,
chemicalSubstance, value, component, stringValue, booleanValue, hexBinaryValue, uriValue, minValue, maxValue,
meanValue, sDev, percRank, percValue, uom))
```

What do you think?

**Comment by RalphTro** [comment]
Update: as of the current master branch, the algorithm behaves as it should from my POV. 

@dakbhavesh: Thanks for sharing your thoughts! As to the wording, I suggest that I will set up an e-mail to Craig about this matter and copy you in (no need to discuss this via GitHub in my view).

**Comment by RalphTro** [comment]
When digging into this matter next week (when you have the bandwidth), please note that even though sensorElementList should not appear several times, sensorElement should (of course, *if* there are multiple contained sensorElements :-))

**Comment by RalphTro** [comment]
Just checked `epcisDocWithSensorDataObjectEvent.jsonld` in the `master `branch. 

Im my opinion, the sequence looks as it should be (removed all irrelevant fields): 

```
sensorElementList

sensorElement
sensorMetadata
sensorReport
sensorReport
sensorReport
sensorReport

sensorElement
sensorMetadata
sensorReport
sensorReport
sensorReport
sensorReport

sensorElement
sensorMetadata
sensorReport
sensorReport
sensorReport
sensorReport
```

So, I think we can close this issue tomorrow.

**Comment by RalphTro** [comment]
Related issue: what happens if sensorElementList contains user extensions? 
Bhavesh to have a look - THANKS!

**Comment by dakbhavesh** [comment]
Thanks, @RalphTro for your quick response. I will look into your observation and fix it as soon as I can.

**Comment by dakbhavesh** [comment]
Dear @RalphTro, I have fixed a glitch in logic. Can you please try running your tests again and see if it's looking better now?

Thanks,
Bhavesh

**Comment by RalphTro** [comment]
Many thanks, @dakbhavesh! 

Taking the above-mentioned example, the user extensions under readPoint/bizLocation now look correct, e.g.:
```
readPointid=https://id.gs1.org/414/4012345000115
{https://ns.ext1.de/epcis/}readPointField2=readPointText2
{https://ns.ext1.de/epcis/}readPointField=readPointText
```
Also, the user extensions under `sensorElement` is correctly appended to the pre-hash string. 

The same holds true for the user extensions in `sensorMetadata` and `sensorReport`.

I tried it out both on Mac and Windows. 

So, all looks good now! *GREAT*! :-)

**Comment by RalphTro** [comment]
Can be closed as of latest PR.
